name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - run: rustup default stable
      - run: cargo fmt --check
      - run: cargo test --workspace
      - run: cargo build --release
      - run: ./target/release/t --version
      - run: cargo run -p xtask -- build-release
